language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest

deploy:
  provider: pypi
  user: $pypi_username
  password: $pypi_pw
  distributions: sdist
  on:
    tags: true
    python: 3.5